### PR TITLE
goquest_service.js: handle all board sizes with state machine

### LINKED ISSUE #3: Support other board sizes: 13 and 19
As I said on the other issue, I have it running as an AWS Lambda on my fork. And it supports all board sizes (just tested on 19x19 boards too).

My code is here: https://github.com/andrewallred/allez/compare/main...maurelio1234:main
Sorry for the lots of whitespace change... I formatted the code at some point. 

I can prepare clean patches.

I suggest starting by bringing the state machine system to allow it to fetch all board sizes.
The main code is around here: https://github.com/andrewallred/allez/compare/main...maurelio1234:main#diff-b9889c22c400de9264d991dae49003241646087095397aaf5b505d135f7976f3R107

What do you think?

### PR DESCRIPTION
**Pull request by maurelio1234**
Fixes #3

### CODE REVIEW

**Comment by andrewallred** [comment]
Reviewing this now to make sure I understand it @maurelio1234. Thanks for putting it together!

**Comment by maurelio1234** [comment]
Rebased

**Comment by andrewallred** [comment]
@maurelio1234 I merged main into this and am having a little bit of trouble, firstly I don't have any 13x13 games so a logging statement was erroring out, but I fixed that with af7e7be63b27679d351d18e1d96fcfbcbd2b689d. Now the error I'm getting is:

`resolve is not defined`

for 

`changeState(resolve);`

Is something possibly missing there?

**Comment by maurelio1234** [comment]
> Is something possibly missing there?

oh yes! it shouldn't be there... it's useful only when running the code async link on my fork. I will remove it.

**Comment by maurelio1234** [comment]
@andrewallred 

Just pushed  some fixes.
I found two unrelated problems so I pushed them in different commits.
I hope the commit messages are clear enough ;)

**Pull request closed without merging**
