### PR TITLE
go-quest-game.js: more descriptive file names

### PR DESCRIPTION
**Pull request by maurelio1234**

### CODE REVIEW

**Comment by andrewallred** [comment]
Hey @maurelio1234, I'm looking at this PR now and reflecting on what users would find easiest. One note while I think on that, I'm currently getting an error in this branch:

> (node:62576) UnhandledPromiseRejectionWarning: TypeError: game.args[0].gtype.replaceAll is not a function

**Comment by maurelio1234** [comment]
Can you log the game.args[0] object for your game? Do you have the link for your game?
Links like this should work: `http://wars.fm/go[BOARDSIZE]#game/[ID]`

**Comment by andrewallred** [comment]
@maurelio1234 

The value for `game.args[0].gtype` is `go9`. I'm thinking this error has something to do with my version of javascript or node 🤔

**Comment by maurelio1234** [comment]
> The value for `game.args[0].gtype` is `go9`. I'm thinking this error has something to do with my version of javascript or node thinking

Yes, replaceAll is node 15+ apparently.
just replaced it by replace... it will work the same on our case.

It wouldn't work on AWS Lambda either... it's node 14.X :'(

**Comment by andrewallred** [comment]
@maurelio1234 I expanded on this a little bit by 1) using a "GoQuest" collection if available instead of adding GoQuest to the game name, and 2) displaying just the time and not the date and time both since OGS already displays the date. (There's also a merge from main into this branch to fix a potential conflict but nothing special there except that the ID is still used *if* the opening is missing for some reason.

I'm going to go ahead and merge this into main, but take a look and let me know what you think!

**Comment by maurelio1234** [comment]
>  2) displaying just the time and not the date and time both since OGS already displays the date. (There's also a merge from main into this branch to fix a potential conflict but nothing special there except that the ID is still used _if_ the opening is missing for some reason.

OGS displays the upload date not the game date, they are not necessarily the same.

**Pull request merged**
